"""Rendering a report to CSV, Excel or PDF (spec section 28).

One structure in, three formats out. Report builders never know which format
was asked for, so a number cannot disagree between the spreadsheet and the PDF.

The rule that matters here is how "no data" travels. Every KPI in this system
returns ``None`` when its denominator is zero -- efficiency with nothing
planned, on-time with nothing completed -- and that is not the same as zero.
Each format expresses it in the way that format's readers expect: an empty
cell in CSV, a genuinely blank cell in Excel so ``AVERAGE`` skips it rather
than dragging the mean towards nothing, and an em dash in the PDF where a human
is reading it.
"""

from __future__ import annotations

import csv
import io
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

#: What a human should see where a metric could not be computed.
DASH = "—"


@dataclass(slots=True)
class Section:
    """One table in a report."""

    title: str
    columns: list[str]
    rows: list[list[Any]]
    #: Shown under the table. Use it to say what the numbers mean or exclude.
    note: str | None = None


@dataclass(slots=True)
class Report:
    key: str
    title: str
    period_label: str
    generated_at: datetime
    generated_by: str | None = None
    #: Headline figures, already labelled. Values follow the same None rule.
    summary: list[tuple[str, Any]] = field(default_factory=list)
    sections: list[Section] = field(default_factory=list)

    @property
    def filename_stem(self) -> str:
        stamp = self.generated_at.strftime("%Y%m%d")
        return f"{self.key}-report-{stamp}"


def to_dict(report: Report) -> dict:
    """JSON form, for the screen that renders the report before exporting it."""
    return {
        "key": report.key,
        "title": report.title,
        "period_label": report.period_label,
        "generated_at": report.generated_at.isoformat(),
        "generated_by": report.generated_by,
        "summary": [{"label": label, "value": value} for label, value in report.summary],
        "sections": [
            {
                "title": section.title,
                "columns": section.columns,
                "rows": section.rows,
                "note": section.note,
            }
            for section in report.sections
        ],
    }


# ---------------------------------------------------------------------------
# CSV
# ---------------------------------------------------------------------------


def to_csv(report: Report) -> bytes:
    """A single CSV holding every section, separated by blank lines.

    One file rather than a zip of sheets: a CSV export is usually opened once
    and skimmed, and a reader who wants the sections apart has Excel.
    """
    buffer = io.StringIO(newline="")
    writer = csv.writer(buffer, lineterminator="\r\n")

    writer.writerow([report.title])
    writer.writerow([report.period_label])
    writer.writerow(["Generated", report.generated_at.strftime("%Y-%m-%d %H:%M")])
    if report.generated_by:
        writer.writerow(["Generated by", report.generated_by])
    writer.writerow([])

    if report.summary:
        writer.writerow(["Summary"])
        for label, value in report.summary:
            writer.writerow([label, "" if value is None else value])
        writer.writerow([])

    for section in report.sections:
        writer.writerow([section.title])
        writer.writerow(section.columns)
        for row in section.rows:
            writer.writerow(["" if cell is None else cell for cell in row])
        if section.note:
            writer.writerow([section.note])
        writer.writerow([])

    # BOM so Excel opens a UTF-8 CSV with the right encoding on a double click
    # instead of mangling any non-ASCII name in it.
    return buffer.getvalue().encode("utf-8-sig")


# ---------------------------------------------------------------------------
# Excel
# ---------------------------------------------------------------------------

_HEADER_FILL = PatternFill("solid", fgColor="1F45DB")
_HEADER_FONT = Font(color="FFFFFF", bold=True, size=10)
_TITLE_FONT = Font(bold=True, size=13)


def _safe_sheet_title(title: str, used: set[str]) -> str:
    """Excel sheet names: 31 characters, no []:*?/\\, and unique."""
    cleaned = "".join(c for c in title if c not in "[]:*?/\\")[:31] or "Sheet"
    candidate = cleaned
    suffix = 2
    while candidate.lower() in used:
        candidate = f"{cleaned[:28]}~{suffix}"
        suffix += 1
    used.add(candidate.lower())
    return candidate


def to_xlsx(report: Report) -> bytes:
    """One sheet of headlines, then one sheet per section."""
    workbook = Workbook()
    used: set[str] = set()

    overview = workbook.active
    overview.title = _safe_sheet_title("Summary", used)
    overview["A1"] = report.title
    overview["A1"].font = _TITLE_FONT
    overview["A2"] = report.period_label
    overview["A3"] = f"Generated {report.generated_at.strftime('%Y-%m-%d %H:%M')}"
    if report.generated_by:
        overview["A4"] = f"Generated by {report.generated_by}"

    row_index = 6
    for label, value in report.summary:
        overview.cell(row=row_index, column=1, value=label)
        # None is written as a blank cell, not 0 and not "—": AVERAGE and SUM
        # skip blanks, which is the honest treatment of a metric that had no
        # denominator.
        overview.cell(row=row_index, column=2, value=value)
        row_index += 1

    overview.column_dimensions["A"].width = 34
    overview.column_dimensions["B"].width = 18

    for section in report.sections:
        sheet = workbook.create_sheet(_safe_sheet_title(section.title, used))
        sheet.append(section.columns)
        for cell in sheet[1]:
            cell.fill = _HEADER_FILL
            cell.font = _HEADER_FONT
            cell.alignment = Alignment(vertical="center")

        for row in section.rows:
            sheet.append(list(row))

        widths = [len(str(column)) for column in section.columns]
        for row in section.rows:
            for index, cell in enumerate(row):
                if index < len(widths):
                    widths[index] = max(widths[index], len(str(cell if cell is not None else "")))
        for index, width in enumerate(widths, start=1):
            sheet.column_dimensions[get_column_letter(index)].width = min(
                max(width + 2, 10), 48
            )

        sheet.freeze_panes = "A2"

        if section.note:
            sheet.append([])
            sheet.append([section.note])

    stream = io.BytesIO()
    workbook.save(stream)
    return stream.getvalue()


# ---------------------------------------------------------------------------
# PDF
# ---------------------------------------------------------------------------


def to_pdf(report: Report) -> bytes:
    """Landscape A4: these tables are wide, and a wrapped table is unreadable."""
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Title"], fontSize=16, alignment=TA_LEFT, spaceAfter=2
    )
    meta_style = ParagraphStyle(
        "ReportMeta", parent=styles["Normal"], fontSize=8.5, textColor=colors.HexColor("#647691")
    )
    section_style = ParagraphStyle(
        "SectionTitle", parent=styles["Heading2"], fontSize=11, spaceBefore=10, spaceAfter=4
    )
    note_style = ParagraphStyle(
        "Note", parent=styles["Normal"], fontSize=7.5, textColor=colors.HexColor("#647691")
    )
    cell_style = ParagraphStyle("Cell", parent=styles["Normal"], fontSize=7.5, leading=9)

    stream = io.BytesIO()
    document = SimpleDocTemplate(
        stream,
        pagesize=landscape(A4),
        leftMargin=14 * mm,
        rightMargin=14 * mm,
        topMargin=12 * mm,
        bottomMargin=12 * mm,
        title=report.title,
    )

    story: list = [
        Paragraph(report.title, title_style),
        Paragraph(report.period_label, meta_style),
        Paragraph(
            f"Generated {report.generated_at.strftime('%d %b %Y, %H:%M')}"
            + (f" by {report.generated_by}" if report.generated_by else ""),
            meta_style,
        ),
        Spacer(1, 8),
    ]

    if report.summary:
        summary_rows = [
            [label, DASH if value is None else str(value)]
            for label, value in report.summary
        ]
        table = Table(summary_rows, colWidths=[70 * mm, 40 * mm], hAlign="LEFT")
        table.setStyle(
            TableStyle(
                [
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#4F5F78")),
                    ("FONTNAME", (1, 0), (1, -1), "Helvetica-Bold"),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                    ("LINEBELOW", (0, 0), (-1, -2), 0.25, colors.HexColor("#ECEEF2")),
                ]
            )
        )
        story.extend([table, Spacer(1, 6)])

    for index, section in enumerate(report.sections):
        if index > 0:
            story.append(PageBreak())
        story.append(Paragraph(section.title, section_style))

        if not section.rows:
            story.append(Paragraph("No rows for this period.", note_style))
            continue

        header = [Paragraph(f"<b>{c}</b>", cell_style) for c in section.columns]
        body = [
            [
                Paragraph(DASH if cell is None else str(cell), cell_style)
                for cell in row
            ]
            for row in section.rows
        ]

        table = Table([header, *body], repeatRows=1, hAlign="LEFT")
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F45DB")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#D5DAE2")),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F6F7F9")]),
                    ("LEFTPADDING", (0, 0), (-1, -1), 4),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ]
            )
        )
        story.append(table)

        if section.note:
            story.extend([Spacer(1, 3), Paragraph(section.note, note_style)])

    document.build(story)
    return stream.getvalue()


RENDERERS = {
    "csv": (to_csv, "text/csv", "csv"),
    "xlsx": (
        to_xlsx,
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "xlsx",
    ),
    "pdf": (to_pdf, "application/pdf", "pdf"),
}
