"""hold reasons, variance reasons and task on hold

Revision ID: 12cd83dcd6db
Revises: deeb5b6e72f8
Create Date: 2026-08-21 14:17:06.280411
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '12cd83dcd6db'
down_revision: str | None = 'deeb5b6e72f8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_releases', sa.Column('hold_reason', sa.String(length=80), nullable=True))
    op.add_column('design_releases', sa.Column('hold_note', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('hold_reason', sa.String(length=80), nullable=True))
    op.add_column('projects', sa.Column('hold_note', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('hold_reason', sa.String(length=80), nullable=True))
    op.add_column('tasks', sa.Column('hold_note', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('variance_reason', sa.String(length=80), nullable=True))
    op.add_column('tasks', sa.Column('variance_note', sa.Text(), nullable=True))
    op.create_index(op.f('ix_tasks_hold_reason'), 'tasks', ['hold_reason'], unique=False)
    op.create_index(op.f('ix_tasks_variance_reason'), 'tasks', ['variance_reason'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_variance_reason'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_hold_reason'), table_name='tasks')
    op.drop_column('tasks', 'variance_note')
    op.drop_column('tasks', 'variance_reason')
    op.drop_column('tasks', 'hold_note')
    op.drop_column('tasks', 'hold_reason')
    op.drop_column('projects', 'hold_note')
    op.drop_column('projects', 'hold_reason')
    op.drop_column('design_releases', 'hold_note')
    op.drop_column('design_releases', 'hold_reason')
    # ### end Alembic commands ###
