"""employee code as a login identity

Revision ID: 32b34baf523f
Revises: 877802e1d894
Create Date: 2026-08-19 22:06:56.877617
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '32b34baf523f'
down_revision: str | None = '877802e1d894'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_code', sa.String(length=40), nullable=True))
    op.create_index(op.f('ix_users_employee_code'), 'users', ['employee_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_employee_code'), table_name='users')
    op.drop_column('users', 'employee_code')
    # ### end Alembic commands ###
