"""The team lead drives the project, not the design manager

Every project has exactly one person driving it and that person is a team lead.
design_manager_id named the department head instead -- and defaulted to whoever
happened to create the project -- which made it a record of who filled in a
form rather than of who is running the work.

Dropping the column rather than leaving it dormant: a field nothing writes and
nothing reads is one somebody eventually trusts. Nothing is lost, because
nothing was there. All 32 projects held NULL in design_manager_id, checked
immediately before this was written, so there is no data to carry across to
team_lead_id.

The two project notifications that used to reach the design manager -- release
completed, project completed -- now reach the team lead, for the same reason:
they should land with whoever is driving the work.

Revision ID: 5fbda7a9cc87
Revises: 194940c730cb
Create Date: 2026-08-26 17:05:29.981777
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '5fbda7a9cc87'
down_revision: str | None = '194940c730cb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_design_manager_id', table_name='projects')
    op.drop_index('ix_projects_manager_status', table_name='projects')
    op.drop_constraint('projects_design_manager_id_fkey', 'projects', type_='foreignkey')
    op.drop_column('projects', 'design_manager_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('design_manager_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('projects_design_manager_id_fkey', 'projects', 'users', ['design_manager_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_projects_manager_status', 'projects', ['design_manager_id', 'status'], unique=False)
    op.create_index('ix_projects_design_manager_id', 'projects', ['design_manager_id'], unique=False)
    # ### end Alembic commands ###
