"""design commitment, dispatch and forecast dates

Revision ID: 6b70f437c3d1
Revises: b905879a9f68
Create Date: 2026-08-21 21:28:08.007989
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '6b70f437c3d1'
down_revision: str | None = 'b905879a9f68'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_releases', sa.Column('dispatch_date', sa.Date(), nullable=True))
    op.add_column('design_releases', sa.Column('forecast_end', sa.Date(), nullable=True))
    op.add_column('design_releases', sa.Column(
            'is_completion_critical',
            sa.Boolean(),
            nullable=False,
            # Existing releases all gate their project until told otherwise;
            # a NOT NULL column cannot be added to populated rows without one.
            server_default=sa.true(),
        ))
    op.create_index(op.f('ix_design_releases_dispatch_date'), 'design_releases', ['dispatch_date'], unique=False)
    op.create_index(op.f('ix_design_releases_forecast_end'), 'design_releases', ['forecast_end'], unique=False)
    op.add_column('projects', sa.Column('forecast_end', sa.Date(), nullable=True))
    op.create_index(op.f('ix_projects_forecast_end'), 'projects', ['forecast_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_forecast_end'), table_name='projects')
    op.drop_column('projects', 'forecast_end')
    op.drop_index(op.f('ix_design_releases_forecast_end'), table_name='design_releases')
    op.drop_index(op.f('ix_design_releases_dispatch_date'), table_name='design_releases')
    op.drop_column('design_releases', 'is_completion_critical')
    op.drop_column('design_releases', 'forecast_end')
    op.drop_column('design_releases', 'dispatch_date')
    # ### end Alembic commands ###
