"""standard design releases per product

Revision ID: 877802e1d894
Revises: cab6f21fcf3b
Create Date: 2026-08-19 16:32:09.249318
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '877802e1d894'
down_revision: str | None = 'cab6f21fcf3b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_standards',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant', sa.String(length=60), nullable=False),
    sa.Column('variant_condition', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('alternative_name', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'variant', 'sequence', name='uq_standard_order')
    )
    op.create_index(op.f('ix_release_standards_created_at'), 'release_standards', ['created_at'], unique=False)
    op.create_index(op.f('ix_release_standards_product_id'), 'release_standards', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_release_standards_product_id'), table_name='release_standards')
    op.drop_index(op.f('ix_release_standards_created_at'), table_name='release_standards')
    op.drop_table('release_standards')
    # ### end Alembic commands ###
