"""baseline dates for a design release

Revision ID: b905879a9f68
Revises: 12cd83dcd6db
Create Date: 2026-08-21 14:31:59.180797
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b905879a9f68'
down_revision: str | None = '12cd83dcd6db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_releases', sa.Column('baseline_planned_start', sa.Date(), nullable=True))
    op.add_column('design_releases', sa.Column('baseline_planned_end', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design_releases', 'baseline_planned_end')
    op.drop_column('design_releases', 'baseline_planned_start')
    # ### end Alembic commands ###
