"""carry the design team's own fields: cars, GFC date, DSQ count

Revision ID: cab6f21fcf3b
Revises: ead5b16cc41d
Create Date: 2026-08-19 12:55:58.160092
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'cab6f21fcf3b'
down_revision: str | None = 'ead5b16cc41d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_releases', sa.Column('dsq_count', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('car_count', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('gfc_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'gfc_date')
    op.drop_column('projects', 'car_count')
    op.drop_column('design_releases', 'dsq_count')
    # ### end Alembic commands ###
