"""how many units a release covers

Revision ID: deeb5b6e72f8
Revises: 32b34baf523f
Create Date: 2026-08-20 11:29:55.649245
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'deeb5b6e72f8'
down_revision: str | None = '32b34baf523f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_releases', sa.Column('unit_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design_releases', 'unit_count')
    # ### end Alembic commands ###
