"""template task dependency can be advisory

Revision ID: ead5b16cc41d
Revises: eb8992997166
Create Date: 2026-08-18 23:00:21.721855
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'ead5b16cc41d'
down_revision: str | None = 'eb8992997166'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_tasks', sa.Column('depends_on_blocking', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_tasks', 'depends_on_blocking')
    # ### end Alembic commands ###
