"""initial design operations schema

Revision ID: eb8992997166
Revises: 
Create Date: 2026-08-18 16:00:09.377680
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'eb8992997166'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('customer_code', sa.String(length=40), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('contact_name', sa.String(length=160), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('external_system', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_code'), 'customers', ['code'], unique=True)
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=True)
    op.create_index(op.f('ix_customers_external_id'), 'customers', ['external_id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_table('document_counters',
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('padding', sa.Integer(), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_counters_created_at'), 'document_counters', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_counters_entity'), 'document_counters', ['entity'], unique=True)
    op.create_table('holidays',
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holiday_date', 'region')
    )
    op.create_index(op.f('ix_holidays_created_at'), 'holidays', ['created_at'], unique=False)
    op.create_index(op.f('ix_holidays_holiday_date'), 'holidays', ['holiday_date'], unique=False)
    op.create_table('integration_records',
    sa.Column('external_system', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('internal_id', sa.UUID(), nullable=False),
    sa.Column('external_object_id', sa.String(length=120), nullable=True),
    sa.Column('external_object_type', sa.String(length=80), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_system', 'entity_type', 'internal_id', name='uq_integration_internal')
    )
    op.create_index('ix_integration_external', 'integration_records', ['external_system', 'entity_type', 'external_object_id'], unique=False)
    op.create_index(op.f('ix_integration_records_created_at'), 'integration_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_integration_records_external_system'), 'integration_records', ['external_system'], unique=False)
    op.create_index(op.f('ix_integration_records_sync_status'), 'integration_records', ['sync_status'], unique=False)
    op.create_table('permissions',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_created_at'), 'permissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_table('product_families',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('external_system', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_families_code'), 'product_families', ['code'], unique=True)
    op.create_index(op.f('ix_product_families_created_at'), 'product_families', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_families_external_id'), 'product_families', ['external_id'], unique=False)
    op.create_index(op.f('ix_product_families_name'), 'product_families', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('skills',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.create_index(op.f('ix_skills_created_at'), 'skills', ['created_at'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('sync_logs',
    sa.Column('external_system', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_created_at'), 'sync_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_sync_logs_status'), 'sync_logs', ['status'], unique=False)
    op.create_index('ix_sync_logs_system_time', 'sync_logs', ['external_system', 'started_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reports_to_id', sa.UUID(), nullable=True),
    sa.Column('standard_daily_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('working_days_per_week', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('external_system', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('standard_daily_hours > 0 AND standard_daily_hours <= 24', name='ck_users_daily_hours_range'),
    sa.ForeignKeyConstraint(['reports_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_active_email', 'users', ['is_active', 'email'], unique=False)
    op.create_index(op.f('ix_users_code'), 'users', ['code'], unique=True)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=False)
    op.create_index(op.f('ix_users_reports_to_id'), 'users', ['reports_to_id'], unique=False)
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_category'), 'app_settings', ['category'], unique=False)
    op.create_index(op.f('ix_app_settings_created_at'), 'app_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
    op.create_table('attachments',
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=160), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_provider', sa.String(length=30), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('external_system', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name='ck_attachment_size_non_negative'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_code'), 'attachments', ['code'], unique=True)
    op.create_index(op.f('ix_attachments_created_at'), 'attachments', ['created_at'], unique=False)
    op.create_index('ix_attachments_entity', 'attachments', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_attachments_external_id'), 'attachments', ['external_id'], unique=False)
    op.create_index(op.f('ix_attachments_uploaded_by_id'), 'attachments', ['uploaded_by_id'], unique=False)
    op.create_index('ix_attachments_version', 'attachments', ['entity_type', 'entity_id', 'file_name', 'version'], unique=False)
    op.create_table('audit_logs',
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('entity_code', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_code'), 'audit_logs', ['entity_code'], unique=False)
    op.create_table('comments',
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True),
    sa.Column('mentions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index('ix_comments_entity', 'comments', ['entity_type', 'entity_id'], unique=False)
    op.create_table('leave_records',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('leave_type', sa.String(length=40), nullable=False),
    sa.Column('hours_per_day', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='ck_leave_date_order'),
    sa.CheckConstraint('hours_per_day > 0', name='ck_leave_hours_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_records_created_at'), 'leave_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_leave_records_end_date'), 'leave_records', ['end_date'], unique=False)
    op.create_index(op.f('ix_leave_records_start_date'), 'leave_records', ['start_date'], unique=False)
    op.create_index(op.f('ix_leave_records_status'), 'leave_records', ['status'], unique=False)
    op.create_index(op.f('ix_leave_records_user_id'), 'leave_records', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_required', sa.Boolean(), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_event_type'), 'notifications', ['event_type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('products',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('product_family_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('external_system', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_family_id'], ['product_families.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_external_id'), 'products', ['external_id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_product_family_id'), 'products', ['product_family_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('status_history',
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=40), nullable=True),
    sa.Column('to_status', sa.String(length=40), nullable=False),
    sa.Column('duration_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_history_changed_at'), 'status_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_status_history_changed_by_id'), 'status_history', ['changed_by_id'], unique=False)
    op.create_index(op.f('ix_status_history_created_at'), 'status_history', ['created_at'], unique=False)
    op.create_index('ix_status_history_entity', 'status_history', ['entity_type', 'entity_id', 'changed_at'], unique=False)
    op.create_index(op.f('ix_status_history_to_status'), 'status_history', ['to_status'], unique=False)
    op.create_table('user_capacity',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('capacity_date', sa.Date(), nullable=False),
    sa.Column('available_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('available_hours >= 0', name='ck_capacity_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'capacity_date')
    )
    op.create_index(op.f('ix_user_capacity_capacity_date'), 'user_capacity', ['capacity_date'], unique=False)
    op.create_index(op.f('ix_user_capacity_created_at'), 'user_capacity', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_capacity_user_id'), 'user_capacity', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id')
    )
    op.create_index(op.f('ix_user_roles_created_at'), 'user_roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('user_skills',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('level_rank', sa.Integer(), nullable=False),
    sa.Column('years_experience', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id')
    )
    op.create_index(op.f('ix_user_skills_created_at'), 'user_skills', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_skills_skill_id'), 'user_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_user_skills_user_id'), 'user_skills', ['user_id'], unique=False)
    op.create_table('design_templates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_family_id', sa.UUID(), nullable=True),
    sa.Column('release_type', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('external_system', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_family_id'], ['product_families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_templates_code'), 'design_templates', ['code'], unique=True)
    op.create_index(op.f('ix_design_templates_created_at'), 'design_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_design_templates_external_id'), 'design_templates', ['external_id'], unique=False)
    op.create_index(op.f('ix_design_templates_name'), 'design_templates', ['name'], unique=False)
    op.create_index(op.f('ix_design_templates_product_family_id'), 'design_templates', ['product_family_id'], unique=False)
    op.create_index(op.f('ix_design_templates_product_id'), 'design_templates', ['product_id'], unique=False)
    op.create_index(op.f('ix_design_templates_release_type'), 'design_templates', ['release_type'], unique=False)
    op.create_index('ix_templates_match', 'design_templates', ['product_id', 'product_family_id', 'release_type'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('project_type', sa.String(length=80), nullable=True),
    sa.Column('sales_order', sa.String(length=80), nullable=True),
    sa.Column('work_order', sa.String(length=80), nullable=True),
    sa.Column('project_manager_id', sa.UUID(), nullable=True),
    sa.Column('design_manager_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('required_completion_date', sa.Date(), nullable=True),
    sa.Column('internal_deadline', sa.Date(), nullable=True),
    sa.Column('customer_deadline', sa.Date(), nullable=True),
    sa.Column('actual_completion_date', sa.Date(), nullable=True),
    sa.Column('planned_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rework_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('completion_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('health', sa.String(length=10), nullable=False),
    sa.Column('health_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('external_system', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_hours >= 0', name='ck_project_actual_hours'),
    sa.CheckConstraint('planned_hours >= 0', name='ck_project_planned_hours'),
    sa.CheckConstraint('required_completion_date IS NULL OR start_date IS NULL OR required_completion_date >= start_date', name='ck_project_date_order'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['design_manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_customer_id'), 'projects', ['customer_id'], unique=False)
    op.create_index(op.f('ix_projects_design_manager_id'), 'projects', ['design_manager_id'], unique=False)
    op.create_index(op.f('ix_projects_external_id'), 'projects', ['external_id'], unique=False)
    op.create_index(op.f('ix_projects_health'), 'projects', ['health'], unique=False)
    op.create_index('ix_projects_manager_status', 'projects', ['design_manager_id', 'status'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_priority'), 'projects', ['priority'], unique=False)
    op.create_index(op.f('ix_projects_product_id'), 'projects', ['product_id'], unique=False)
    op.create_index(op.f('ix_projects_project_manager_id'), 'projects', ['project_manager_id'], unique=False)
    op.create_index(op.f('ix_projects_project_type'), 'projects', ['project_type'], unique=False)
    op.create_index(op.f('ix_projects_required_completion_date'), 'projects', ['required_completion_date'], unique=False)
    op.create_index(op.f('ix_projects_sales_order'), 'projects', ['sales_order'], unique=False)
    op.create_index(op.f('ix_projects_start_date'), 'projects', ['start_date'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index('ix_projects_status_health', 'projects', ['status', 'health'], unique=False)
    op.create_index(op.f('ix_projects_work_order'), 'projects', ['work_order'], unique=False)
    op.create_table('design_template_versions',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by_id', sa.UUID(), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version_number > 0', name='ck_template_version_positive'),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['design_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version_number', name='uq_template_version')
    )
    op.create_index(op.f('ix_design_template_versions_created_at'), 'design_template_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_design_template_versions_template_id'), 'design_template_versions', ['template_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_role', sa.String(length=60), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_members_created_at'), 'project_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index('ix_project_members_unique', 'project_members', ['project_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('design_releases',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('release_type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('template_version_id', sa.UUID(), nullable=True),
    sa.Column('team_lead_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_end', sa.Date(), nullable=True),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_end', sa.Date(), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rework_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('completion_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('health', sa.String(length=10), nullable=False),
    sa.Column('health_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('delay_reason', sa.String(length=80), nullable=True),
    sa.Column('delay_note', sa.Text(), nullable=True),
    sa.Column('completion_override_by_id', sa.UUID(), nullable=True),
    sa.Column('completion_override_reason', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('external_system', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_hours >= 0', name='ck_release_actual_hours'),
    sa.CheckConstraint('estimated_hours >= 0', name='ck_release_estimated_hours'),
    sa.CheckConstraint('planned_end IS NULL OR planned_start IS NULL OR planned_end >= planned_start', name='ck_release_date_order'),
    sa.CheckConstraint('sequence_number > 0', name='ck_release_sequence_positive'),
    sa.ForeignKeyConstraint(['completion_override_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_lead_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_version_id'], ['design_template_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'sequence_number', name='uq_release_sequence')
    )
    op.create_index(op.f('ix_design_releases_code'), 'design_releases', ['code'], unique=True)
    op.create_index(op.f('ix_design_releases_created_at'), 'design_releases', ['created_at'], unique=False)
    op.create_index(op.f('ix_design_releases_external_id'), 'design_releases', ['external_id'], unique=False)
    op.create_index(op.f('ix_design_releases_health'), 'design_releases', ['health'], unique=False)
    op.create_index(op.f('ix_design_releases_name'), 'design_releases', ['name'], unique=False)
    op.create_index(op.f('ix_design_releases_planned_end'), 'design_releases', ['planned_end'], unique=False)
    op.create_index(op.f('ix_design_releases_planned_start'), 'design_releases', ['planned_start'], unique=False)
    op.create_index(op.f('ix_design_releases_priority'), 'design_releases', ['priority'], unique=False)
    op.create_index(op.f('ix_design_releases_product_id'), 'design_releases', ['product_id'], unique=False)
    op.create_index(op.f('ix_design_releases_project_id'), 'design_releases', ['project_id'], unique=False)
    op.create_index(op.f('ix_design_releases_release_type'), 'design_releases', ['release_type'], unique=False)
    op.create_index(op.f('ix_design_releases_status'), 'design_releases', ['status'], unique=False)
    op.create_index(op.f('ix_design_releases_team_lead_id'), 'design_releases', ['team_lead_id'], unique=False)
    op.create_index(op.f('ix_design_releases_template_version_id'), 'design_releases', ['template_version_id'], unique=False)
    op.create_index('ix_releases_lead_status', 'design_releases', ['team_lead_id', 'status'], unique=False)
    op.create_index('ix_releases_project_status', 'design_releases', ['project_id', 'status'], unique=False)
    op.create_table('template_tasks',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('task_type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_estimated_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('default_priority', sa.String(length=20), nullable=False),
    sa.Column('complexity', sa.Integer(), nullable=False),
    sa.Column('required_skill_id', sa.UUID(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('depends_on_sequence', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('default_estimated_hours >= 0', name='ck_template_task_hours_non_negative'),
    sa.ForeignKeyConstraint(['required_skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['design_template_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'sequence', name='uq_template_task_sequence')
    )
    op.create_index(op.f('ix_template_tasks_created_at'), 'template_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_template_tasks_required_skill_id'), 'template_tasks', ['required_skill_id'], unique=False)
    op.create_index(op.f('ix_template_tasks_task_type'), 'template_tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_template_tasks_version_id'), 'template_tasks', ['version_id'], unique=False)
    op.create_table('tasks',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('release_id', sa.UUID(), nullable=False),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('template_task_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=80), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('team_lead_id', sa.UUID(), nullable=True),
    sa.Column('required_skill_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('complexity', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_end', sa.Date(), nullable=True),
    sa.Column('original_estimated_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('estimated_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('rework_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('blocked_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('completion_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('submission_count', sa.Integer(), nullable=False),
    sa.Column('blocker_reason', sa.Text(), nullable=True),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('delay_reason', sa.String(length=80), nullable=True),
    sa.Column('delay_note', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('external_system', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_hours >= 0', name='ck_task_actual_non_negative'),
    sa.CheckConstraint('completion_percent >= 0 AND completion_percent <= 100', name='ck_task_completion_range'),
    sa.CheckConstraint('complexity BETWEEN 1 AND 5', name='ck_task_complexity_range'),
    sa.CheckConstraint('estimated_hours >= 0', name='ck_task_estimated_non_negative'),
    sa.CheckConstraint('planned_end IS NULL OR planned_start IS NULL OR planned_end >= planned_start', name='ck_task_date_order'),
    sa.CheckConstraint('rework_hours >= 0', name='ck_task_rework_non_negative'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['design_releases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['required_skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_lead_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_task_id'], ['template_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_to_id'), 'tasks', ['assigned_to_id'], unique=False)
    op.create_index('ix_tasks_assignee_status', 'tasks', ['assigned_to_id', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_code'), 'tasks', ['code'], unique=True)
    op.create_index(op.f('ix_tasks_completed_at'), 'tasks', ['completed_at'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_delay_reason'), 'tasks', ['delay_reason'], unique=False)
    op.create_index('ix_tasks_due', 'tasks', ['status', 'planned_end'], unique=False)
    op.create_index(op.f('ix_tasks_external_id'), 'tasks', ['external_id'], unique=False)
    op.create_index(op.f('ix_tasks_name'), 'tasks', ['name'], unique=False)
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_tasks_planned_end'), 'tasks', ['planned_end'], unique=False)
    op.create_index(op.f('ix_tasks_planned_start'), 'tasks', ['planned_start'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_release_id'), 'tasks', ['release_id'], unique=False)
    op.create_index('ix_tasks_release_status', 'tasks', ['release_id', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_required_skill_id'), 'tasks', ['required_skill_id'], unique=False)
    op.create_index(op.f('ix_tasks_review_status'), 'tasks', ['review_status'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_tasks_team_lead_id'), 'tasks', ['team_lead_id'], unique=False)
    op.create_table('reviews',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('release_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('submitted_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('review_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('turnaround_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('external_system', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['design_releases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_code'), 'reviews', ['code'], unique=True)
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_external_id'), 'reviews', ['external_id'], unique=False)
    op.create_index(op.f('ix_reviews_project_id'), 'reviews', ['project_id'], unique=False)
    op.create_index(op.f('ix_reviews_release_id'), 'reviews', ['release_id'], unique=False)
    op.create_index(op.f('ix_reviews_result'), 'reviews', ['result'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.create_index('ix_reviews_reviewer_status', 'reviews', ['reviewer_id', 'status'], unique=False)
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_index(op.f('ix_reviews_submitted_at'), 'reviews', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_reviews_task_id'), 'reviews', ['task_id'], unique=False)
    op.create_index('ix_reviews_task_round', 'reviews', ['task_id', 'round_number'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_task_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.String(length=30), nullable=False),
    sa.Column('is_blocking', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('task_id <> depends_on_task_id', name='ck_no_self_dependency'),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on_task_id', name='uq_task_dependency')
    )
    op.create_index(op.f('ix_task_dependencies_created_at'), 'task_dependencies', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_dependencies_depends_on_task_id'), 'task_dependencies', ['depends_on_task_id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_task_id'), 'task_dependencies', ['task_id'], unique=False)
    op.create_table('task_estimate_history',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('previous_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('new_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_estimate_history_created_at'), 'task_estimate_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_estimate_history_task_id'), 'task_estimate_history', ['task_id'], unique=False)
    op.create_table('revisions',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('release_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('review_id', sa.UUID(), nullable=True),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('accountability', sa.String(length=20), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raised_by_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('raised_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('additional_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('external_system', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('additional_hours >= 0', name='ck_revision_hours_non_negative'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raised_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['release_id'], ['design_releases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revisions_accountability'), 'revisions', ['accountability'], unique=False)
    op.create_index(op.f('ix_revisions_assigned_to_id'), 'revisions', ['assigned_to_id'], unique=False)
    op.create_index('ix_revisions_assignee', 'revisions', ['assigned_to_id', 'status'], unique=False)
    op.create_index(op.f('ix_revisions_category'), 'revisions', ['category'], unique=False)
    op.create_index(op.f('ix_revisions_code'), 'revisions', ['code'], unique=True)
    op.create_index(op.f('ix_revisions_created_at'), 'revisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_revisions_external_id'), 'revisions', ['external_id'], unique=False)
    op.create_index(op.f('ix_revisions_project_id'), 'revisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_revisions_raised_date'), 'revisions', ['raised_date'], unique=False)
    op.create_index(op.f('ix_revisions_release_id'), 'revisions', ['release_id'], unique=False)
    op.create_index(op.f('ix_revisions_status'), 'revisions', ['status'], unique=False)
    op.create_index('ix_revisions_status_category', 'revisions', ['status', 'category'], unique=False)
    op.create_index(op.f('ix_revisions_task_id'), 'revisions', ['task_id'], unique=False)
    op.create_table('time_entries',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('release_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('is_rework', sa.Boolean(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('external_system', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at', name='ck_time_entry_interval_order'),
    sa.CheckConstraint('hours >= 0', name='ck_time_entry_hours_non_negative'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['design_releases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_entries_code'), 'time_entries', ['code'], unique=True)
    op.create_index(op.f('ix_time_entries_created_at'), 'time_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_time_entries_entry_date'), 'time_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_time_entries_external_id'), 'time_entries', ['external_id'], unique=False)
    op.create_index(op.f('ix_time_entries_project_id'), 'time_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_time_entries_release_id'), 'time_entries', ['release_id'], unique=False)
    op.create_index('ix_time_entries_running', 'time_entries', ['user_id', 'is_running'], unique=False)
    op.create_index('ix_time_entries_task', 'time_entries', ['task_id', 'entry_date'], unique=False)
    op.create_index(op.f('ix_time_entries_task_id'), 'time_entries', ['task_id'], unique=False)
    op.create_index('ix_time_entries_user_date', 'time_entries', ['user_id', 'entry_date'], unique=False)
    op.create_index(op.f('ix_time_entries_user_id'), 'time_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_entries_user_id'), table_name='time_entries')
    op.drop_index('ix_time_entries_user_date', table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_task_id'), table_name='time_entries')
    op.drop_index('ix_time_entries_task', table_name='time_entries')
    op.drop_index('ix_time_entries_running', table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_release_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_project_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_external_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_entry_date'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_created_at'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_code'), table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_index(op.f('ix_revisions_task_id'), table_name='revisions')
    op.drop_index('ix_revisions_status_category', table_name='revisions')
    op.drop_index(op.f('ix_revisions_status'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_release_id'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_raised_date'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_project_id'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_external_id'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_created_at'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_code'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_category'), table_name='revisions')
    op.drop_index('ix_revisions_assignee', table_name='revisions')
    op.drop_index(op.f('ix_revisions_assigned_to_id'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_accountability'), table_name='revisions')
    op.drop_table('revisions')
    op.drop_index(op.f('ix_task_estimate_history_task_id'), table_name='task_estimate_history')
    op.drop_index(op.f('ix_task_estimate_history_created_at'), table_name='task_estimate_history')
    op.drop_table('task_estimate_history')
    op.drop_index(op.f('ix_task_dependencies_task_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_depends_on_task_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_created_at'), table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index('ix_reviews_task_round', table_name='reviews')
    op.drop_index(op.f('ix_reviews_task_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_submitted_at'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_index('ix_reviews_reviewer_status', table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_result'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_release_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_project_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_external_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_code'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_tasks_team_lead_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_review_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_required_skill_id'), table_name='tasks')
    op.drop_index('ix_tasks_release_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_release_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_planned_start'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_planned_end'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_name'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_external_id'), table_name='tasks')
    op.drop_index('ix_tasks_due', table_name='tasks')
    op.drop_index(op.f('ix_tasks_delay_reason'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_completed_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_code'), table_name='tasks')
    op.drop_index('ix_tasks_assignee_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_template_tasks_version_id'), table_name='template_tasks')
    op.drop_index(op.f('ix_template_tasks_task_type'), table_name='template_tasks')
    op.drop_index(op.f('ix_template_tasks_required_skill_id'), table_name='template_tasks')
    op.drop_index(op.f('ix_template_tasks_created_at'), table_name='template_tasks')
    op.drop_table('template_tasks')
    op.drop_index('ix_releases_project_status', table_name='design_releases')
    op.drop_index('ix_releases_lead_status', table_name='design_releases')
    op.drop_index(op.f('ix_design_releases_template_version_id'), table_name='design_releases')
    op.drop_index(op.f('ix_design_releases_team_lead_id'), table_name='design_releases')
    op.drop_index(op.f('ix_design_releases_status'), table_name='design_releases')
    op.drop_index(op.f('ix_design_releases_release_type'), table_name='design_releases')
    op.drop_index(op.f('ix_design_releases_project_id'), table_name='design_releases')
    op.drop_index(op.f('ix_design_releases_product_id'), table_name='design_releases')
    op.drop_index(op.f('ix_design_releases_priority'), table_name='design_releases')
    op.drop_index(op.f('ix_design_releases_planned_start'), table_name='design_releases')
    op.drop_index(op.f('ix_design_releases_planned_end'), table_name='design_releases')
    op.drop_index(op.f('ix_design_releases_name'), table_name='design_releases')
    op.drop_index(op.f('ix_design_releases_health'), table_name='design_releases')
    op.drop_index(op.f('ix_design_releases_external_id'), table_name='design_releases')
    op.drop_index(op.f('ix_design_releases_created_at'), table_name='design_releases')
    op.drop_index(op.f('ix_design_releases_code'), table_name='design_releases')
    op.drop_table('design_releases')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index('ix_project_members_unique', table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_created_at'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_design_template_versions_template_id'), table_name='design_template_versions')
    op.drop_index(op.f('ix_design_template_versions_created_at'), table_name='design_template_versions')
    op.drop_table('design_template_versions')
    op.drop_index(op.f('ix_projects_work_order'), table_name='projects')
    op.drop_index('ix_projects_status_health', table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_start_date'), table_name='projects')
    op.drop_index(op.f('ix_projects_sales_order'), table_name='projects')
    op.drop_index(op.f('ix_projects_required_completion_date'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_type'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_manager_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_product_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_priority'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index('ix_projects_manager_status', table_name='projects')
    op.drop_index(op.f('ix_projects_health'), table_name='projects')
    op.drop_index(op.f('ix_projects_external_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_design_manager_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_customer_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_templates_match', table_name='design_templates')
    op.drop_index(op.f('ix_design_templates_release_type'), table_name='design_templates')
    op.drop_index(op.f('ix_design_templates_product_id'), table_name='design_templates')
    op.drop_index(op.f('ix_design_templates_product_family_id'), table_name='design_templates')
    op.drop_index(op.f('ix_design_templates_name'), table_name='design_templates')
    op.drop_index(op.f('ix_design_templates_external_id'), table_name='design_templates')
    op.drop_index(op.f('ix_design_templates_created_at'), table_name='design_templates')
    op.drop_index(op.f('ix_design_templates_code'), table_name='design_templates')
    op.drop_table('design_templates')
    op.drop_index(op.f('ix_user_skills_user_id'), table_name='user_skills')
    op.drop_index(op.f('ix_user_skills_skill_id'), table_name='user_skills')
    op.drop_index(op.f('ix_user_skills_created_at'), table_name='user_skills')
    op.drop_table('user_skills')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_created_at'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_capacity_user_id'), table_name='user_capacity')
    op.drop_index(op.f('ix_user_capacity_created_at'), table_name='user_capacity')
    op.drop_index(op.f('ix_user_capacity_capacity_date'), table_name='user_capacity')
    op.drop_table('user_capacity')
    op.drop_index(op.f('ix_status_history_to_status'), table_name='status_history')
    op.drop_index('ix_status_history_entity', table_name='status_history')
    op.drop_index(op.f('ix_status_history_created_at'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_changed_by_id'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_changed_at'), table_name='status_history')
    op.drop_table('status_history')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_products_product_family_id'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_external_id'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_table('products')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_leave_records_user_id'), table_name='leave_records')
    op.drop_index(op.f('ix_leave_records_status'), table_name='leave_records')
    op.drop_index(op.f('ix_leave_records_start_date'), table_name='leave_records')
    op.drop_index(op.f('ix_leave_records_end_date'), table_name='leave_records')
    op.drop_index(op.f('ix_leave_records_created_at'), table_name='leave_records')
    op.drop_table('leave_records')
    op.drop_index('ix_comments_entity', table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_audit_logs_entity_code'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_index('ix_audit_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_attachments_version', table_name='attachments')
    op.drop_index(op.f('ix_attachments_uploaded_by_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_external_id'), table_name='attachments')
    op.drop_index('ix_attachments_entity', table_name='attachments')
    op.drop_index(op.f('ix_attachments_created_at'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_code'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_index(op.f('ix_app_settings_created_at'), table_name='app_settings')
    op.drop_index(op.f('ix_app_settings_category'), table_name='app_settings')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_users_reports_to_id'), table_name='users')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_code'), table_name='users')
    op.drop_index('ix_users_active_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_sync_logs_system_time', table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_status'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_created_at'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_created_at'), table_name='skills')
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_product_families_name'), table_name='product_families')
    op.drop_index(op.f('ix_product_families_external_id'), table_name='product_families')
    op.drop_index(op.f('ix_product_families_created_at'), table_name='product_families')
    op.drop_index(op.f('ix_product_families_code'), table_name='product_families')
    op.drop_table('product_families')
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_created_at'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_integration_records_sync_status'), table_name='integration_records')
    op.drop_index(op.f('ix_integration_records_external_system'), table_name='integration_records')
    op.drop_index(op.f('ix_integration_records_created_at'), table_name='integration_records')
    op.drop_index('ix_integration_external', table_name='integration_records')
    op.drop_table('integration_records')
    op.drop_index(op.f('ix_holidays_holiday_date'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_created_at'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_document_counters_entity'), table_name='document_counters')
    op.drop_index(op.f('ix_document_counters_created_at'), table_name='document_counters')
    op.drop_table('document_counters')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_external_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.drop_index(op.f('ix_customers_code'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
